var files =
[
    [ "src/AF.cpp", "AF_8cpp.html", null ],
    [ "src/AF.h", null, null ],
    [ "src/Argument.cpp", "Argument_8cpp.html", "Argument_8cpp" ],
    [ "src/Argument.h", null, null ],
    [ "src/Boundcond.cpp", null, null ],
    [ "src/Boundcond.h", null, null ],
    [ "src/ExtendedArgument.cpp", "ExtendedArgument_8cpp.html", "ExtendedArgument_8cpp" ],
    [ "src/ExtendedArgument.h", null, null ],
    [ "src/Grounded.cpp", "Grounded_8cpp.html", null ],
    [ "src/Grounded.h", null, null ],
    [ "src/Labelling.cpp", "Labelling_8cpp.html", "Labelling_8cpp" ],
    [ "src/Labelling.h", null, null ],
    [ "src/main.cpp", null, null ],
    [ "src/misc.cpp", "misc_8cpp.html", "misc_8cpp" ],
    [ "src/OrClause.cpp", "OrClause_8cpp.html", "OrClause_8cpp" ],
    [ "src/OrClause.h", null, null ],
    [ "src/PrefAlgorithm.cpp", null, null ],
    [ "src/PrefAlgorithm.h", null, null ],
    [ "src/Preferred.cpp", null, null ],
    [ "src/Preferred.h", "Preferred_8h.html", "Preferred_8h" ],
    [ "src/SATFormulae.cpp", "SATFormulae_8cpp.html", "SATFormulae_8cpp" ],
    [ "src/SATFormulae.h", null, null ],
    [ "src/SCCSEQ.cpp", "SCCSEQ_8cpp.html", null ],
    [ "src/SCCSEQ.h", null, null ],
    [ "src/semopt.h", "semopt_8h.html", "semopt_8h" ],
    [ "src/SetArguments.cpp", "SetArguments_8cpp.html", "SetArguments_8cpp" ],
    [ "src/SetArguments.h", null, null ],
    [ "src/SetArgumentsVector.cpp", "SetArgumentsVector_8cpp.html", "SetArgumentsVector_8cpp" ],
    [ "src/SetArgumentsVector.h", null, null ]
];